name: NuGet.Services.EndToEnd CI $(BuildId)

trigger:
  branches:
    include:
    - '*'
  batch: True

variables:
- name: BuildConfiguration
  value: Release
- name: Codeql.Enabled
  value: true
- name: nugetMultiFeedWarnLevel
  value: none
- name: NugetSecurityAnalysisWarningLevel
  value: none
- name: PackageVersion
  value: $(SimplePackageVersion)$(PrereleaseVersion)
- name: PrereleaseVersion
  value: -$(NuGetServicesE2EBranch)-$(Build.BuildId)
- name: SimplePackageVersion
  value: 1.0.0
- name: NuGetServicesE2EDirectory
  value: nse
- name: NuGetServicesE2EPath
  value: $(Agent.BuildDirectory)\$(NuGetServicesE2EDirectory)
- name: ArtifactsFolder
  value: $(NuGetServicesE2EPath)\artifacts
- name: NuGetServicesE2EBranch
  value: $(Build.SourceBranchName)

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NuGet-1ES-Hosted-Pool
      image: NuGet-1ESPT-Win2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Phase 1
        cancelTimeoutInMinutes: 1
        steps:
        - checkout: self
          fetchDepth: 1
          clean: true
          fetchTags: false
          path: $(NuGetServicesE2EDirectory)
        - task: PowerShell@1
          name: PowerShell_1
          displayName: Build
          inputs:
            scriptName: $(NuGetServicesE2EPath)\build.ps1
            workingFolder: $(NuGetServicesE2EPath)
        - task: PowerShell@1
          name: PowerShell_2
          displayName: Run unit tests
          inputs:
            scriptName: $(NuGetServicesE2EPath)\test.ps1
            arguments: -OnlyUnitTests
            workingFolder: $(NuGetServicesE2EPath)
        - task: PublishTestResults@1
          name: PublishTestResults_3
          displayName: Publish Test Results Results.*.xml
          condition: succeededOrFailed()
          inputs:
            testRunner: XUnit
            testResultsFiles: $(NuGetServicesE2EPath)\Results.*.xml
